// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(LifeDexDbContext))]
    [Migration("20260707003058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Database.DbModels.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogueOfLifeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxonColId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueOfLifeId");

                    b.HasIndex("TaxonColId");

                    b.ToTable("Distributions");
                });

            modelBuilder.Entity("Database.DbModels.Taxon", b =>
                {
                    b.Property<string>("ColId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalExtantVerified")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genus")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsExtinct")
                        .HasColumnType("TEXT");

                    b.Property<string>("Order")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phylum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubPhylum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ColId");

                    b.ToTable("Taxa");
                });

            modelBuilder.Entity("Database.DbModels.VernacularName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogueOfLifeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxonColId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueOfLifeId");

                    b.HasIndex("TaxonColId");

                    b.ToTable("VernacularNames");
                });

            modelBuilder.Entity("Database.DbModels.Distribution", b =>
                {
                    b.HasOne("Database.DbModels.Taxon", null)
                        .WithMany("Distributions")
                        .HasForeignKey("TaxonColId");
                });

            modelBuilder.Entity("Database.DbModels.VernacularName", b =>
                {
                    b.HasOne("Database.DbModels.Taxon", null)
                        .WithMany("VernacularNames")
                        .HasForeignKey("TaxonColId");
                });

            modelBuilder.Entity("Database.DbModels.Taxon", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("VernacularNames");
                });
#pragma warning restore 612, 618
        }
    }
}
