// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(LifeDexDbContext))]
    partial class LifeDexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Database.DbModels.ColDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColId");

                    b.ToTable("ColDistributions");
                });

            modelBuilder.Entity("Database.DbModels.GbifAnnualOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Occurrences")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ColId", "CountryCode", "Year")
                        .IsUnique();

                    b.ToTable("GbifAnnualOccurrences");
                });

            modelBuilder.Entity("Database.DbModels.Taxon", b =>
                {
                    b.Property<string>("ColId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalExtantVerified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsExtinct")
                        .HasColumnType("TEXT");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phylum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubPhylum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ColId");

                    b.ToTable("Taxa");
                });

            modelBuilder.Entity("Database.DbModels.VernacularName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transliteration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColId");

                    b.HasIndex("Language");

                    b.ToTable("VernacularNames");
                });

            modelBuilder.Entity("Database.DbModels.ColDistribution", b =>
                {
                    b.HasOne("Database.DbModels.Taxon", null)
                        .WithMany("ColDistributions")
                        .HasForeignKey("ColId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.DbModels.GbifAnnualOccurrence", b =>
                {
                    b.HasOne("Database.DbModels.Taxon", null)
                        .WithMany("GbifAnnualOccurrences")
                        .HasForeignKey("ColId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.DbModels.VernacularName", b =>
                {
                    b.HasOne("Database.DbModels.Taxon", null)
                        .WithMany("VernacularNames")
                        .HasForeignKey("ColId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.DbModels.Taxon", b =>
                {
                    b.Navigation("ColDistributions");

                    b.Navigation("GbifAnnualOccurrences");

                    b.Navigation("VernacularNames");
                });
#pragma warning restore 612, 618
        }
    }
}
