// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(LifeDexDbContext))]
    partial class LifeDexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Database.DbModels.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogueOfLifeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeciesColId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueOfLifeId");

                    b.HasIndex("SpeciesColId");

                    b.ToTable("Distributions");
                });

            modelBuilder.Entity("Database.DbModels.Species", b =>
                {
                    b.Property<string>("ColId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genus")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsExtinct")
                        .HasColumnType("TEXT");

                    b.Property<string>("Order")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phylum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ColId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Database.DbModels.VernacularName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogueOfLifeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeciesColId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueOfLifeId");

                    b.HasIndex("SpeciesColId");

                    b.ToTable("VernacularNames");
                });

            modelBuilder.Entity("Database.DbModels.Distribution", b =>
                {
                    b.HasOne("Database.DbModels.Species", null)
                        .WithMany("Distributions")
                        .HasForeignKey("SpeciesColId");
                });

            modelBuilder.Entity("Database.DbModels.VernacularName", b =>
                {
                    b.HasOne("Database.DbModels.Species", null)
                        .WithMany("VernacularNames")
                        .HasForeignKey("SpeciesColId");
                });

            modelBuilder.Entity("Database.DbModels.Species", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("VernacularNames");
                });
#pragma warning restore 612, 618
        }
    }
}
